/**
 *   * Alipay.com Inc.  * Copyright (c) 2004-2019 All Rights Reserved.
 */
package com.antgroup.openspg.app.infra.dao.mapper;

import java.util.List;

import com.antgroup.openspg.app.infra.dao.dataobject.permission.RoleDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgRolePO
     * @return int
     */
    int insert(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param id java.lang.Long
     * @return int
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param ids List<Long>
     * @return int
     */
    int deleteByIds(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgRolePO
     * @return int
     */
    int updateByPrimaryKeySelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param id java.lang.Long
     * @return com.alipay.kgmng.common.dal.mybatis.po.KgRolePO
     */
    RoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgRolePO
     * @param start int
     * @param size int
     * @return List<KgRolePO>
     */
    List<RoleDO> selectByCondition(@Param("record") RoleDO record, @Param("start") int start, @Param("size") int size);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgRolePO
     * @return int
     */
    int selectCountByCondition(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_role
     *
     * @param ids List<Long>
     * @return List<KgRolePO>
     */
    List<RoleDO> selectByIds(@Param("ids") List<Long> ids);

    /**
     * roleName
     * @param roleName
     * @return
     */
    RoleDO selectByRoleName(@Param("roleName") String roleName);
}