/**
 *   * Alipay.com Inc.  * Copyright (c) 2004-2019 All Rights Reserved.
 */
package com.antgroup.openspg.app.infra.dao.mapper;

import java.util.List;

import com.antgroup.openspg.app.infra.dao.dataobject.permission.UserResourceRoleDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * kgUserResourceRole mapper类
 * @author nanmu
 */
@Mapper
public interface UserResourceRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserResourceRolePO
     * @return int
     */
    int insert(UserResourceRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param id java.lang.Long
     * @return int
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param ids List<Long>
     * @return int
     */
    int deleteByIds(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserResourceRolePO
     * @return int
     */
    int updateByPrimaryKeySelective(UserResourceRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param id java.lang.Long
     * @return com.alipay.kgmng.common.dal.mybatis.po.KgUserResourceRolePO
     */
    UserResourceRoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserResourceRolePO
     * @param start int
     * @param size int
     * @return List<KgUserResourceRolePO>
     */
    List<UserResourceRoleDO> selectByCondition(@Param("record") UserResourceRoleDO record, @Param("start") int start,
                                               @Param("size") int size);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserResourceRolePO
     * @return int
     */
    int selectCountByCondition(UserResourceRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_user_resource_role
     *
     * @param ids List<Long>
     * @return List<KgUserResourceRolePO>
     */
    List<UserResourceRoleDO> selectByIds(@Param("ids") List<Long> ids);

    /**
     * 批量插入数据
     * @param records
     * @return
     */
    int batchInsert(@Param("records") List<UserResourceRoleDO> records);

    /**
     * uodate KgUserResourceRole
     * @param record
     * @return
     */
    int updateResourceRole(@Param("record") UserResourceRoleDO record);

    /**
     * 删除
     * @param record
     * @return
     */
    int deleteByResourceIdAndUserNo(@Param("record") UserResourceRoleDO record);

    /**
     * 删除用户权限
     * @param userNo
     * @return
     */
    int deleteByUserNo(@Param("userNo") String userNo);

    /**
     * 查询所有符合条件的记录
     * @param record
     * @return
     */
    List<UserResourceRoleDO> selectAllByCondition(@Param("record") UserResourceRoleDO record);

    /**
     * 查询权限
     * @param userNo
     * @param resourceId
     * @param resourceTag
     * @return
     */
    UserResourceRoleDO selectUserTypeRoleForUpdate(@Param("userNo") String userNo, @Param("resourceId") Long resourceId,
                                                   @Param("resourceTag") String resourceTag);

    /**
     * 查询具有指定权限的记录
     * @param userId
     * @param roleIds
     * @param resourceTag
     * @return
     */
    List<UserResourceRoleDO> selectByRoleId(@Param("userId") String userId, @Param("roleIds") List<Long> roleIds, @Param("resourceTag") String resourceTag);

    /**
     * 删除资源对应的记录
     * @param resourceId
     * @param resourceTag
     * @return
     */
    int deleteByResourceId(@Param("resourceId") Long resourceId, @Param("resourceTag") String resourceTag);

    int deletePermission(UserResourceRoleDO record);


    /**
     * 批量查询资产权限信息
     * @param resourceIds
     * @param resourceTag
     * @return
     */
    List<UserResourceRoleDO> selectByResources(@Param("resourceIds") List<Long> resourceIds, @Param("resourceTag") String resourceTag);

    /**
     * 根据userNo和角色名称查询资源
     * @param userNo
     * @param roleName
     * @return
     */
    List<UserResourceRoleDO> getResourceIdByUserNoAndRoleName(@Param("userNo")String userNo,
                                                              @Param("resourceTag") String resourceTag,
                                                              @Param("roleName") String roleName);

    /**
     * 查询项目下所有资源权限
     * @param resourceIds
     * @return
     */
    List<UserResourceRoleDO> getByResourceIds(@Param("resourceIds")List<Long> resourceIds, @Param("roleId")Long roleId);
    
    /**
     * 删除项目下所有资源权限
     * @param userIds
     * @param resourceIds
     * @param resourceTag
     * @return
     */
    int deleteByResourceIds(@Param("userIds")List<Long> userIds, @Param("resourceIds")List<Long> resourceIds, @Param("resourceTag") String resourceTag);
}