/*
 * Copyright 2023 Ant Group CO., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 */

/**
 *   * Alipay.com Inc.  * Copyright (c) 2004-2019 All Rights Reserved.
 */
package com.antgroup.openspg.app.infra.dao.mapper;

import com.antgroup.openspg.app.infra.dao.dataobject.account.UserDO;
import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserPO
   * @return int
   */
  int insert(UserDO record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param id java.lang.Long
   * @return int
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param ids List<Long>
   * @return int
   */
  int deleteByIds(@Param("ids") List<Long> ids);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserPO
   * @return int
   */
  int updateByPrimaryKeySelective(UserDO record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param id java.lang.Long
   * @return com.alipay.kgmng.common.dal.mybatis.po.KgUserPO
   */
  UserDO selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserPO
   * @param start int
   * @param size int
   * @return List<KgUserPO>
   */
  List<UserDO> selectByCondition(
      @Param("record") UserDO record, @Param("start") int start, @Param("size") int size);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param record com.alipay.kgmng.common.dal.mybatis.po.KgUserPO
   * @return int
   */
  int selectCountByCondition(UserDO record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * kg_user
   *
   * @param ids List<Long>
   * @return List<KgUserPO>
   */
  List<UserDO> selectByIds(@Param("ids") List<Long> ids);

  /**
   * 根据userNo查询
   *
   * @param userNo
   * @return
   */
  UserDO getByUserId(@Param("userNo") String userNo);

  List<UserDO> getByUserIdList(@Param("userNoList") List<String> userNoList);

  int updateToken(UserDO record);

  int updateAccessKey(UserDO record);

  int cleanLastToken(@Param("userNo") String userNo);

  int deleteByUser(@Param("userNo") String userNo);

  /**
   * 补全用户信息
   *
   * @param record
   * @return
   */
  int completeUserInfo(UserDO record);

  /**
   * 批量按员工号获取员工信息
   *
   * @param ids
   * @return
   */
  List<UserDO> getSimpleUserByUserNoList(@Param("ids") Collection<String> ids);

  /**
   * 根据工号或域账号或者名称模糊查询
   *
   * @param keyWord
   * @return
   */
  List<UserDO> getUserLikeUserNoOrDomainNoOrName(@Param("keyWord") String keyWord);
}
