/*
 * Copyright 2023 Ant Group CO., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 */

/**
 *   * Alipay.com Inc.  * Copyright (c) 2004-2019 All Rights Reserved.
 */
package com.antgroup.openspg.app.infra.dao.dataobject.permission;

import java.util.Date;

/**
 * This model corresponds to the database table: kg_project_member_role_info Database Table Remarks:
 */
public class ProjectMemberRoleInfoDO {
  /** 主键 */
  private Long id;

  /** 角色唯一标识 */
  private Long roleId;

  /** 项目唯一标识 */
  private Long projectId;

  /** 用户工号 */
  private String userNo;

  /** DELETE:删除 VALID:有效 INVALID：无效 */
  private String status;

  /** 创建时间 */
  private Date gmtCreate;

  /** 修改时间 */
  private Date gmtModified;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.id
   *
   * @return the value of kg_project_member_role_info.id
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.id
   *
   * @param id the value for kg_project_member_role_info.id
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.role_id
   *
   * @return the value of kg_project_member_role_info.role_id
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public Long getRoleId() {
    return roleId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.role_id
   *
   * @param roleId the value for kg_project_member_role_info.role_id
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setRoleId(Long roleId) {
    this.roleId = roleId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.project_id
   *
   * @return the value of kg_project_member_role_info.project_id
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public Long getProjectId() {
    return projectId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.project_id
   *
   * @param projectId the value for kg_project_member_role_info.project_id
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.user_no
   *
   * @return the value of kg_project_member_role_info.user_no
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public String getUserNo() {
    return userNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.user_no
   *
   * @param userNo the value for kg_project_member_role_info.user_no
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setUserNo(String userNo) {
    this.userNo = userNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.status
   *
   * @return the value of kg_project_member_role_info.status
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.status
   *
   * @param status the value for kg_project_member_role_info.status
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.gmt_create
   *
   * @return the value of kg_project_member_role_info.gmt_create
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public Date getGmtCreate() {
    return gmtCreate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.gmt_create
   *
   * @param gmtCreate the value for kg_project_member_role_info.gmt_create
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setGmtCreate(Date gmtCreate) {
    this.gmtCreate = gmtCreate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column kg_project_member_role_info.gmt_modified
   *
   * @return the value of kg_project_member_role_info.gmt_modified
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public Date getGmtModified() {
    return gmtModified;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column kg_project_member_role_info.gmt_modified
   *
   * @param gmtModified the value for kg_project_member_role_info.gmt_modified
   * @mbg.generated Tue Apr 28 17:32:23 CST 2020
   */
  public void setGmtModified(Date gmtModified) {
    this.gmtModified = gmtModified;
  }
}
