/**
 *   * Alipay.com Inc.  * Copyright (c) 2004-2019 All Rights Reserved.
 */
package com.antgroup.openspg.app.infra.dao.dataobject.permission;

import java.util.Date;

/**
 * This model corresponds to the database table: kg_user_resource_role
 * Database Table Remarks:
 * 
 */
public class UserResourceRoleDO {
    /**
     * 主键
     */
    private Long id;

    /**
     * 创建时间
     */
    private Date gmtCreate;

    /**
     * 修改时间
     */
    private Date gmtModified;

    /**
     * 用户工号
     */
    private String userNo;

    /**
     * 资源id
     */
    private Long resourceId;

    /**
     * 角色id
     */
    private Long roleId;

    /**
     * 资源分类
     */
    private String resourceTag;

    /**
     * 状态。-1：驳回;99：审批中;1：有效;9：删除
     */
    private String status;

    /**
     * 过期日期
     */
    private Date expireDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.id
     *
     * @return the value of kg_user_resource_role.id
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.id
     *
     * @param id the value for kg_user_resource_role.id
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.gmt_create
     *
     * @return the value of kg_user_resource_role.gmt_create
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.gmt_create
     *
     * @param gmtCreate the value for kg_user_resource_role.gmt_create
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.gmt_modified
     *
     * @return the value of kg_user_resource_role.gmt_modified
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.gmt_modified
     *
     * @param gmtModified the value for kg_user_resource_role.gmt_modified
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.user_no
     *
     * @return the value of kg_user_resource_role.user_no
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.user_no
     *
     * @param userNo the value for kg_user_resource_role.user_no
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.resource_id
     *
     * @return the value of kg_user_resource_role.resource_id
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.resource_id
     *
     * @param resourceId the value for kg_user_resource_role.resource_id
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.role_id
     *
     * @return the value of kg_user_resource_role.role_id
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.role_id
     *
     * @param roleId the value for kg_user_resource_role.role_id
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.resource_tag
     *
     * @return the value of kg_user_resource_role.resource_tag
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public String getResourceTag() {
        return resourceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.resource_tag
     *
     * @param resourceTag the value for kg_user_resource_role.resource_tag
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setResourceTag(String resourceTag) {
        this.resourceTag = resourceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.status
     *
     * @return the value of kg_user_resource_role.status
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.status
     *
     * @param status the value for kg_user_resource_role.status
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kg_user_resource_role.expire_date
     *
     * @return the value of kg_user_resource_role.expire_date
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kg_user_resource_role.expire_date
     *
     * @param expireDate the value for kg_user_resource_role.expire_date
     *
     * @mbg.generated Wed Mar 25 10:54:59 CST 2020
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
}